version: '3.7'
services:
  
  nginx-app:
    image: tiredofit/nginx:latest
    container_name: nginx-app
    labels:
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-app.rule=Host(`nginx.example.com`)
      - traefik.http.services.nginx-app.loadbalancer.server.port=80
    volumes:
      - ./data:/www/html
      - ./logs:/www/logs
    environment:
      - ZABBIX_HOSTNAME=nginx-ldap-app
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
