# Manual Workflow tiredofit/docker-nginx
name: manual

on:
  workflow_dispatch:
    inputs:
      Manual Build:
        description: 'Manual Build'
        required: false
          build-args: |
             DEBIAN_VERSION=${{ env.RELEASE }}
